In [2]:
import pandas as pd
df=pd.DataFrame({
    'st_name': ['Anu','Rahul','Aju','Hiba','Ritha','Sanu','Unni'],
    'attendance': [34,56,12,90,65,43,21],
    'marks': [56,43,34,21,89,45,67],
    'dept': ['cs','mech','ec','cs','ec','cs','ec']
})
print(df)

  st_name  attendance  marks  dept
0     Anu          34     56    cs
1   Rahul          56     43  mech
2     Aju          12     34    ec
3    Hiba          90     21    cs
4   Ritha          65     89    ec
5    Sanu          43     45    cs
6    Unni          21     67    ec

In [25]:
# 1 find the first 5 students

print(df.head())

    Marks
s3     65
s2     45
s1     23
s4     12

In [30]:
# 2 find the total no of students

print(df['st_name'].count())

7

In [34]:
# 3.find the highest mark

print(df['marks'].max())

89

In [33]:
# 4 find the lowest mark.

print(df['marks'].min())

21

In [32]:
# 5 find the avg mark

print(df['marks'].mean())

50.714285714285715

FILTERING

In [44]:
# 6 display the cs students

df[df['dept']=='cs']

  st_name  attendance  marks dept
0     Anu          34     56   cs
3    Hiba          90     21   cs
5    Sanu          43     45   cs

SORTING

In [ ]:
# 7  Find the name of the student who scored highest mark.

a=df.sort_values('marks',ascending=False)
a['st_name'].head(1)

# print(df.sort_values('marks',ascending=False).head(1)['st_name'])

IndexError: invalid index to scalar variable.

In [38]:
# 8 Find the student with lowest attendance
b=df.sort_values('attendance',ascending=True)
b.head(1)

  st_name  attendance  marks dept
2     Aju          12     34   ec

In [40]:
# 9 Display the students who scored above 80.

df[df['marks']>80]

  st_name  attendance  marks dept
4   Ritha          65     89   ec

In [41]:
# 10 find the top 3 students based on the mark.

a.head(3)

  st_name  attendance  marks dept
4   Ritha          65     89   ec
6    Unni          21     67   ec
0     Anu          34     56   cs

In [42]:
# 11 Find the bottom 3 students based on the mark.
a.tail(3)

  st_name  attendance  marks  dept
1   Rahul          56     43  mech
2     Aju          12     34    ec
3    Hiba          90     21    cs

In [43]:
# 12 Sort the student according to study hour.

print(b)

  st_name  attendance  marks  dept
2     Aju          12     34    ec
6    Unni          21     67    ec
0     Anu          34     56    cs
5    Sanu          43     45    cs
1   Rahul          56     43  mech
4   Ritha          65     89    ec
3    Hiba          90     21    cs

In [ ]:
# 13 Find the average mark department wise.


# BY FILTERING 

c=df[df['dept']=='cs']
print(f"CS is",c['marks'].mean())

d=df[df['dept']=='ec']
print(f"EC is",c['marks'].mean())

c=df[df['dept']=='mech']
print(f"mech is",c['marks'].mean())


# BY USING GROUP BY

CS is 40.666666666666664
EC is 40.666666666666664
mech is 43.0

In [50]:
# 14 Find the average attendance department wise.

c=df[df['dept']=='cs']
print(f"CS is",c['attendance'].mean())
d=df[df['dept']=='ec']
print(f"EC is",c['attendance'].mean())
c=df[df['dept']=='mech']
print(f"mech is",c['attendance'].mean())

CS is 55.666666666666664
EC is 55.666666666666664
mech is 56.0

In [52]:
# 15 Find the number of student in each department.

c=df[df['dept']=='cs']
print(f"CS is",c['st_name'].count())
d=df[df['dept']=='ec']
print(f"EC is",c['st_name'].count())
c=df[df['dept']=='mech']
print(f"mech is",c['st_name'].count())

CS is 3
EC is 3
mech is 1

In [ ]:
# 16 Find the department with highest average mark.

c=df[df['dept']=='cs']
d=c['marks'].mean()

e=df[df['dept']=='ec']
f=c['marks'].mean()

g=df[df['dept']=='mech']
h=c['marks'].mean()

In [ ]:
# 17 Display the statistical information about the dataset.

In [ ]:
# Create a dataframe of 4x1, name the columns as marks.

import pandas as pd
df=pd.DataFrame({
    'Marks': [23,45,65,12]
}, index=['s1','s2','s3','s4'])
print(f"Original: \n",df)
print('')
print(f"Default Sort:\n ",df.sort_values('Marks'))
print('')
print(f"Ascending:\n ",df.sort_values('Marks',ascending=True))
print('')
print(f"Descending:\n ",df.sort_values('Marks',ascending=False))
print("")
print(f"First value:\n ",df.head(1))
print("")
print(df.loc['s4',:])

Original:
     Marks
s1     23
s2     45
s3     65
s4     12

Default Sort:
      Marks
s4     12
s1     23
s2     45
s3     65

Ascending:
      Marks
s4     12
s1     23
s2     45
s3     65

Descending:
      Marks
s3     65
s2     45
s1     23
s4     12

    Marks
s1     23

Marks    12
Name: s4, dtype: int64

In [ ]:
df=df.sort_values('Marks',ascending=False)
print(df.tail(1))

    Marks
s4     12

In [ ]:
print(df['Marks']>50)
print("------------------------")
df[df['Marks']>50]
print("------------------------")

s3     True
s2    False
s1    False
s4    False
Name: Marks, dtype: bool
------------------------

    Marks
s3     65

In [22]:
# Create a dataframe
ad=pd.DataFrame({
    'Name':['a','b','c'],
    'Age':[23,56,78],
    'Mark':[12,54,32]
})
print(ad)
print("")
print(ad['Name']=='c')
print("")
print(ad[(ad['Mark']<50)&(ad['Age']>45)])

  Name  Age  Mark
0    a   23    12
1    b   56    54
2    c   78    32

0    False
1    False
2     True
Name: Name, dtype: bool

  Name  Age  Mark
2    c   78    32