In [2]:
# Create a dataframe of 7 rows and 6 columns.columns are name,dept,mobile_no,working_hrs,city,salary.

import pandas as pd
df=pd.DataFrame({
    'st_name': ['anu','hiba','aju','niju','chikku','naja','ritha'],
    'dept':['cse','eee','it','hr','cse','it','eee'],
    'mobile_no':[1234,4321,6789,9876,10934,67234,78342],
    'working_hrs': [9,12,5,7,3,9,5],
    'city': ['kochi','hyderabad','chennai','mumbai','banglore','kochi','hyderabad'],
    'salary': [10000,20000,50000,5000,78000,7800,3000]
})
print(df)
print("")
print(df.groupby('city'))
print("")
print(df.groupby('dept')['salary'])

  st_name dept  mobile_no  working_hrs       city  salary
0     anu  cse       1234            9      kochi   10000
1    hiba  eee       4321           12  hyderabad   20000
2     aju   it       6789            5    chennai   50000
3    niju   hr       9876            7     mumbai    5000
4  chikku  cse      10934            3   banglore   78000
5    naja   it      67234            9      kochi    7800
6   ritha  eee      78342            5  hyderabad    3000

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000010E2AB33F20>

<pandas.core.groupby.generic.SeriesGroupBy object at 0x0000010E2A369910>

In [3]:
print(df.groupby('dept')['salary'].mean())

dept
cse    44000.0
eee    11500.0
hr      5000.0
it     28900.0
Name: salary, dtype: float64

In [4]:
print(df.groupby('dept')['salary'].max())

dept
cse    78000
eee    20000
hr      5000
it     50000
Name: salary, dtype: int64

In [5]:
print(df.groupby('dept')['salary'].min())

dept
cse    10000
eee     3000
hr      5000
it      7800
Name: salary, dtype: int64

In [6]:
print(df.groupby('dept')['salary'].sum())

dept
cse    88000
eee    23000
hr      5000
it     57800
Name: salary, dtype: int64

In [7]:
df.groupby('dept')['salary'].agg(['max','min','sum'])

        max    min    sum
dept
cse   78000  10000  88000
eee   20000   3000  23000
hr     5000   5000   5000
it    50000   7800  57800

DIFFERENT COLUMN, DIFFERENT FUNCTION

In [8]:
df.agg({
    'salary':'max',
    'working_hrs':'min'
})

salary         78000
working_hrs        3
dtype: int64

In [9]:
df.groupby('dept').agg({
    'salary': 'max',
    'working_hrs': 'min'
})

      salary  working_hrs
dept
cse    78000            3
eee    20000            5
hr      5000            7
it     50000            5

different function on the same column

In [10]:
df.agg(
    max_sal=('salary','max'),  
    mean_sal=('salary','mean')
)

                salary
max_sal   78000.000000
mean_sal  24828.571429

SORT VALUES

In [11]:
result=df.groupby('dept')['salary'].max()
print(result.sort_values(ascending=True))
print("")
print(result.sort_values(ascending=False))

dept
hr      5000
eee    20000
it     50000
cse    78000
Name: salary, dtype: int64

dept
cse    78000
it     50000
eee    20000
hr      5000
Name: salary, dtype: int64

In [2]:
# Create a dataframe Name,City,Occupation,clg_name,dept,salary.
# 1.group by city and find minimum salary.
# 2.group by names and sort it by city.
# 3.Group by name and convert their occupation into uppercase.

import pandas as pd
df=pd.DataFrame({
    'name': ['anu','hiba','aju','chikku','chinju'],
    'city': ['kochi','calicut','hyderabad','kochi','hyderabad'],
    'occupation':['driver','teacher','teacher','gardener','driver'],
    'clg_name':['abc','xyz','abc','cvd','cvd'],
    'dept': ['it','hr','it','mech','mech'],
})
df

     name       city occupation clg_name  dept
0     anu      kochi     driver      abc    it
1    hiba    calicut    teacher      xyz    hr
2     aju  hyderabad    teacher      abc    it
3  chikku      kochi   gardener      cvd  mech
4  chinju  hyderabad     driver      cvd  mech

In [4]:
# 1.group by city and find minimum salary.

df['salary']=[20000,40000,40000,25000,20000]
print(df)
print("")
df.groupby('city')['salary'].min()

     name       city occupation clg_name  dept  salary
0     anu      kochi     driver      abc    it   20000
1    hiba    calicut    teacher      xyz    hr   40000
2     aju  hyderabad    teacher      abc    it   40000
3  chikku      kochi   gardener      cvd  mech   25000
4  chinju  hyderabad     driver      cvd  mech   20000

city
calicut      40000
hyderabad    20000
kochi        20000
Name: salary, dtype: int64

In [21]:
# 2.group by names and sort it by city.


a=df.groupby('name')['city'].agg(
    lambda x: x.sort_values(ascending=True)
)
a

name
aju       hyderabad
anu           kochi
chikku        kochi
chinju    hyderabad
hiba        calicut
Name: city, dtype: object

In [8]:
# 3.Group by name and convert their occupation into uppercase.

df.groupby('name')['occupation'].agg(
    lambda x: x.str.upper()
)

name
aju        TEACHER
anu         DRIVER
chikku    GARDENER
chinju      DRIVER
hiba       TEACHER
Name: occupation, dtype: object