In [11]:
# Create a DataFrame of 4x3, column with values city,population,no_of_socail_welfare_worker.

import pandas as pd
df=pd.DataFrame({
    'city': ['Kochi','Chennai',None,'Kochi'],
    'population': [123,564,347,367],
    'no_of_socail_welfare_worker': [34,57,31,12]
})
print(df)

      city  population  no_of_socail_welfare_worker
0    Kochi         123                           34
1  Chennai         564                           57
2     None         347                           31
3    Kochi         367                           12

In [12]:
# To count Unique values.

df['city'].value_counts()

city
Kochi      2
Chennai    1
Name: count, dtype: int64

In [18]:
# To find the percentage

print(df['population'].value_counts(normalize=True))
print("")
print(df['population'].value_counts(normalize=True)*100)

population
123    0.25
564    0.25
347    0.25
367    0.25
Name: proportion, dtype: float64

population
123    25.0
564    25.0
347    25.0
367    25.0
Name: proportion, dtype: float64

In [22]:
# To Include missing values

df['city'].value_counts(dropna=False)

city
Kochi      2
Chennai    1
None       1
Name: count, dtype: int64

In [15]:
# No of unique values

df['city'].nunique()

2

In [20]:
# To get unique values

print(df['city'].unique())

['Kochi' 'Chennai' None]

In [37]:
# Create 2 dataframe 

a=pd.DataFrame({
    'name': ['Arathy','Neha'],
    'age': [13,22]
})
print(a)
print("")
b=pd.DataFrame({
    'maths': [30,27],
    'science': [26,20]
})
print(b)
print("")
print(pd.concat([a,b]))
print("")
print(pd.concat([a,b],ignore_index=True))
print("")
print(pd.concat([a,b],axis=1))

     name  age
0  Arathy   13
1    Neha   22

   maths  science
0     30       26
1     27       20

     name   age  maths  science
0  Arathy  13.0    NaN      NaN
1    Neha  22.0    NaN      NaN
0     NaN   NaN   30.0     26.0
1     NaN   NaN   27.0     20.0

     name   age  maths  science
0  Arathy  13.0    NaN      NaN
1    Neha  22.0    NaN      NaN
2     NaN   NaN   30.0     26.0
3     NaN   NaN   27.0     20.0

     name  age  maths  science
0  Arathy   13     30       26
1    Neha   22     27       20

In [41]:
# Create 2 dataframe and merge based on their ID.

c=pd.DataFrame({
    'ID': [0,1],
    'name': ['Arathy','Neha']
})
print(c)
print("")
d=pd.DataFrame({
    'ID': [1,2],
    'mark': [26,20]
})
print(d)
print("")
pd.merge(c,d,on="ID")

   ID    name
0   0  Arathy
1   1    Neha

   ID  mark
0   1    26
1   2    20

   ID  name  mark
0   1  Neha    26

In [63]:
# Create a dataframe of student with their details of name,age,father's_name,mother's_name,mobile_no and their Id.
# Create a student details with st_id,st_name,class,test1,test2,mobile_no.
# 5 rows

st_p=pd.DataFrame({
    'st_name':['anu','hiba','neha','ichu','niju'],
    'age':[21,23,45,67,43],
    'father_name': ['biju','shiju','unni','hari','shareef'],
    'mother_name':['bindu','sindhu','sheeba','shyma','rajula'],
    'mobile_no': [1234,4321,56789,98765,1230],
    'st_id': [101,102,103,104,105]
})
print(st_p)
st_d=pd.DataFrame({
    'st_id': [105,104,110,102,101],
    'st_name':['niju','ichu','neha','hiba','anu'],
    'class':['cse','ece','cse','mech','eee'],
    'test1': [12,21,20,17,15],
    'test2': [11,10,8,15,16],
    'mobile_no': [1230,1672,56789,4321,1234],
})
print("")
print(st_d)
print("")

  st_name  age father_name mother_name  mobile_no  st_id
0     anu   21        biju       bindu       1234    101
1    hiba   23       shiju      sindhu       4321    102
2    neha   45        unni      sheeba      56789    103
3    ichu   67        hari       shyma      98765    104
4    niju   43     shareef      rajula       1230    105

   st_id st_name class  test1  test2  mobile_no
0    105    niju   cse     12     11       1230
1    104    ichu   ece     21     10       1672
2    110    neha   cse     20      8      56789
3    102    hiba  mech     17     15       4321
4    101     anu   eee     15     16       1234

In [64]:
pd.merge(st_p,st_d,on='st_id')

,st_name_x,age,father_name,mother_name,mobile_no_x,st_id,st_name_y,class,test1,test2,mobile_no_y
0,anu,21,biju,bindu,1234,101,anu,eee,15,16,1234
1,hiba,23,shiju,sindhu,4321,102,hiba,mech,17,15,4321
2,ichu,67,hari,shyma,98765,104,ichu,ece,21,10,1672
3,niju,43,shareef,rajula,1230,105,niju,cse,12,11,1230

In [65]:
pd.merge(st_p,st_d,on='st_name')

,st_name,age,father_name,mother_name,mobile_no_x,st_id_x,st_id_y,class,test1,test2,mobile_no_y
0,anu,21,biju,bindu,1234,101,101,eee,15,16,1234
1,hiba,23,shiju,sindhu,4321,102,102,mech,17,15,4321
2,neha,45,unni,sheeba,56789,103,110,cse,20,8,56789
3,ichu,67,hari,shyma,98765,104,104,ece,21,10,1672
4,niju,43,shareef,rajula,1230,105,105,cse,12,11,1230

In [66]:
pd.merge(st_p,st_d,on='mobile_no')

,st_name_x,age,father_name,mother_name,mobile_no,st_id_x,st_id_y,st_name_y,class,test1,test2
0,anu,21,biju,bindu,1234,101,101,anu,eee,15,16
1,hiba,23,shiju,sindhu,4321,102,102,hiba,mech,17,15
2,neha,45,unni,sheeba,56789,103,110,neha,cse,20,8
3,niju,43,shareef,rajula,1230,105,105,niju,cse,12,11

In [67]:
pd.merge(st_p,st_d,on='st_id',how='left')

,st_name_x,age,father_name,mother_name,mobile_no_x,st_id,st_name_y,class,test1,test2,mobile_no_y
0,anu,21,biju,bindu,1234,101,anu,eee,15.0,16.0,1234.0
1,hiba,23,shiju,sindhu,4321,102,hiba,mech,17.0,15.0,4321.0
2,neha,45,unni,sheeba,56789,103,NaN,NaN,NaN,NaN,NaN
3,ichu,67,hari,shyma,98765,104,ichu,ece,21.0,10.0,1672.0
4,niju,43,shareef,rajula,1230,105,niju,cse,12.0,11.0,1230.0

In [68]:
pd.merge(st_p,st_d,on='st_id',how='right')

,st_name_x,age,father_name,mother_name,mobile_no_x,st_id,st_name_y,class,test1,test2,mobile_no_y
0,niju,43.0,shareef,rajula,1230.0,105,niju,cse,12,11,1230
1,ichu,67.0,hari,shyma,98765.0,104,ichu,ece,21,10,1672
2,NaN,NaN,NaN,NaN,NaN,110,neha,cse,20,8,56789
3,hiba,23.0,shiju,sindhu,4321.0,102,hiba,mech,17,15,4321
4,anu,21.0,biju,bindu,1234.0,101,anu,eee,15,16,1234

In [69]:
pd.merge(st_p,st_d,on='st_id',how='inner')

,st_name_x,age,father_name,mother_name,mobile_no_x,st_id,st_name_y,class,test1,test2,mobile_no_y
0,anu,21,biju,bindu,1234,101,anu,eee,15,16,1234
1,hiba,23,shiju,sindhu,4321,102,hiba,mech,17,15,4321
2,ichu,67,hari,shyma,98765,104,ichu,ece,21,10,1672
3,niju,43,shareef,rajula,1230,105,niju,cse,12,11,1230

In [70]:
pd.merge(st_p,st_d,on='st_id',how='outer')

,st_name_x,age,father_name,mother_name,mobile_no_x,st_id,st_name_y,class,test1,test2,mobile_no_y
0,anu,21.0,biju,bindu,1234.0,101,anu,eee,15.0,16.0,1234.0
1,hiba,23.0,shiju,sindhu,4321.0,102,hiba,mech,17.0,15.0,4321.0
2,neha,45.0,unni,sheeba,56789.0,103,NaN,NaN,NaN,NaN,NaN
3,ichu,67.0,hari,shyma,98765.0,104,ichu,ece,21.0,10.0,1672.0
4,niju,43.0,shareef,rajula,1230.0,105,niju,cse,12.0,11.0,1230.0
5,NaN,NaN,NaN,NaN,NaN,110,neha,cse,20.0,8.0,56789.0